// Implexus Powerlifting — weekly change log
// Written automatically by scripts/scrape.mjs each Wednesday.
// prevRankActive / prevRankAll: slug -> last week's rank in each view,
//   used to draw position arrows on the board.
// pbEvents: this week's personal-best improvements, shown as callout cards
//   in dynamic mode. Cleared and rewritten every run.
// generated: ISO timestamp of the run that produced this file.

const CHANGES = {
  "generated": "2026-06-21T13:01:25.792Z",
  "prevRankActive": {
    "wyliesung": 1,
    "mikejones1": 2,
    "genevievecollins": 3,
    "chrisjennings": 4,
    "benthornes": 5,
    "kairichardson": 6,
    "peterking1": 7,
    "anthonywhite1": 8,
    "nickjohnstone": 9,
    "taliafirth": 10,
    "stevewhittles": 11,
    "williamwebb1": 12,
    "leemccafferty": 13,
    "ashlingkeeble": 14,
    "joecurzon": 15,
    "chloeboomer": 16,
    "tobysolomon": 17,
    "finndavis": 18,
    "matthewanderson2": 19,
    "owencrisp": 20,
    "johncousins1": 21,
    "robjacobs": 22,
    "jodiebarnsley": 23,
    "jacklarkinsthomas": 24,
    "laurajones6": 25
  },
  "prevRankAll": {
    "wyliesung": 1,
    "mikejones1": 2,
    "anneburns": 3,
    "maxguo": 4,
    "victoriahart": 5,
    "chrisonuoha": 6,
    "gerryleepierre": 7,
    "genevievecollins": 8,
    "chrisjennings": 9,
    "joshhinchcliffe": 10,
    "benthornes": 11,
    "karldaniel": 12,
    "kairichardson": 13,
    "peterking1": 14,
    "bradycrooks": 15,
    "anthonymclaughlin1": 16,
    "anthonywhite1": 17,
    "samriddharanjan": 18,
    "nickjohnstone": 19,
    "taliafirth": 20,
    "stevewhittles": 21,
    "leohannan": 22,
    "williamwebb1": 23,
    "leemccafferty": 24,
    "alexshortland": 25,
    "ashlingkeeble": 26,
    "joecurzon": 27,
    "chloeboomer": 28,
    "tobysolomon": 29,
    "finndavis": 30,
    "matthewanderson2": 31,
    "owencrisp": 32,
    "samlusher": 33,
    "johncousins1": 34,
    "robjacobs": 35,
    "roryturnbull": 36,
    "kellybroadbent": 37,
    "jodiebarnsley": 38,
    "jacklarkinsthomas": 39,
    "laurajones6": 40
  },
  "pbEvents": []
};
